### PR TITLE
Upgrade all dependencies

### PR DESCRIPTION
**Pull request by Sterahi**
There seems to be an issue with MetaMask not appearing locally, but after confirming the config in `wallet.ts` I'm assuming there's some server magic going on.

### CODE REVIEW

**Comment by oed** [comment]
This doesn't appear to update the `package.json` file, which we should do.

> There seems to be an issue with MetaMask not appearing locally

What do you mean by this?

**Comment by Sterahi** [comment]
@oed 
1. Strange that the package.json didn't get updated with the .lock but I've done it manually & added it. 
2. It's a bit of a strange problem, I've confirmed that my files are identical to what's live but when I go to connect a wallet I just get what's in the following image. 
Screen Shot 2021-07-05 at 11 45 15 AM

**Review by PaulLeCam — COMMENTED** [review]
Seems this PR switches from npm to yarn as well? If so, better also remove the current `package-lock.json` file to avoid confusion.

**Comment by Sterahi** [comment]
@PaulLeCam Good catch, removed yarnlock & updated the npm lock

**Review by oed — APPROVED** [review]
Thanks!

> Strange that the package.json didn't get updated with the .lock but I've done it manually & added it.

Normally you have to manually update package.json. 

> It's a bit of a strange problem, I've confirmed that my files are identical to what's live but when I go to connect a wallet I just get what's in the following image.

What's the problem you are experiencing exactly?

**Comment by Sterahi** [comment]
@oed The issue that I'm having is that I can't confirm that the MetaMask integration is working from my local because the option isn't showing up and it doesn't seem to be in any of our files here on GitHub. Even the live files are the same as my local files but the MetaMask connection option isn't showing up.

**Review by PaulLeCam — APPROVED** [review]

**Comment by Sterahi** [comment]
Sorted out the problem with MetaMask. The auth option is injected into the Web3Modal but it will not show up locally if it's not on a server. Tested it on a server and it's behaving as expected

**Pull request merged**
